---
- name: Overlay timeout configuration file
  tags: timeout
  become: true
  template:
    src: "timeout.sh.j2"
    dest: "/etc/profile.d/timeout.sh"
    owner: root
    group: root
    mode: 0644
