---
- name: Replace login.defs with the compliant one
  template:
      src: "login.defs.j2"
      dest: "/etc/login.defs"
      owner: root
      group: root
      mode: "0644"
  tags:
    - logindefinitions
